## DMA engines
snd-soc-dma-sh7760-objs	:= dma-sh7760.o
obj-$(CONFIG_SND_SOC_PCM_SH7760)	+= snd-soc-dma-sh7760.o

## audio units found on some SH-4
snd-soc-hac-objs	:= hac.o
snd-soc-ssi-objs	:= ssi.o
obj-$(CONFIG_SND_SOC_SH4_HAC)	+= snd-soc-hac.o
obj-$(CONFIG_SND_SOC_SH4_SSI)	+= snd-soc-ssi.o

## boards
snd-soc-exmmb-ac97-objs	:= exmmb-ac97.o
snd-soc-exmmb-i2s-objs	:= exmmb-i2s.o

obj-$(CONFIG_SND_EXMMB7760_AC97) += snd-soc-exmmb-ac97.o
obj-$(CONFIG_SND_EXMMB7760_SSI)	+= snd-soc-exmmb-i2s.o
