#
# Makefile for the Linux SuperH-specific device drivers.
#

obj-$(CONFIG_PCI)		+= pci/
obj-$(CONFIG_SH_DMA)		+= dma/
obj-$(CONFIG_SUPERHYWAY)	+= superhyway/
obj-$(CONFIG_PUSH_SWITCH)	+= push-switch.o
obj-$(CONFIG_HEARTBEAT)		+= heartbeat.o
obj-$(CONFIG_CPU_SUBTYPE_SH7760)+= dmabrg.o
