# i.MX Platform Support
snd-soc-imx21-objs := imx21-pcm.o
snd-soc-imx31-objs := imx31-pcm.o
snd-soc-imx-ac97-objs := imx-ac97.o
snd-soc-imx-ssi-objs := imx-ssi.o

obj-$(CONFIG_SND_MXC_SOC) += snd-soc-imx31.o
obj-$(CONFIG_SND_MXC_SOC_AC97) += snd-soc-imx-ac97.o
obj-$(CONFIG_SND_MXC_SOC_SSI) += snd-soc-imx-ssi.o

# i.MX Machine Support
snd-soc-mx31ads-wm8753-objs := mx31ads_wm8753.o
obj-$(CONFIG_SND_SOC_MX31ADS_WM8753) += snd-soc-mx31ads-wm8753.o
snd-soc-mx21ads-wm8731-objs := mx21ads_wm8731.o
obj-$(CONFIG_SND_SOC_MX21ADS_WM8731) += snd-soc-mx21ads-wm8731.o