# i.MX Platform Support
snd-soc-imx21-objs := imx21-pcm.o
snd-soc-imx31-objs := imx31-pcm.o
snd-soc-imx-ac97-objs := imx-ac97.o
snd-soc-imx-ssi-objs := imx-ssi.o

obj-$(CONFIG_SND_MXC_SOC) += snd-soc-imx31.o
obj-$(CONFIG_SND_MXC_SOC_AC97) += snd-soc-imx-ac97.o
obj-$(CONFIG_SND_MXC_SOC_SSI) += snd-soc-imx-ssi.o

# i.MX Machine Support

