obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery.o	\
				sec_fuelgauge.o
				
obj-$(CONFIG_FUELGAUGE_MAX17048)	+= max17048_fuelgauge.o
obj-$(CONFIG_CHARGER_MAX77803)  += max77803_charger.o charge_control.o
