#
# Makefile for nfc devices
#

obj-$(CONFIG_PN544_NFC)		+= pn544.o
obj-$(CONFIG_NFC_PN533)		+= pn533.o
obj-$(CONFIG_NFC_WILINK)	+= nfcwilink.o
obj-$(CONFIG_PN65N_NFC)		+= pn65n.o
obj-$(CONFIG_BCM2079X_NFC_I2C)	+= bcm2079x-i2c.o
ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG
