#
# Makefile for sensor chip drivers.
#

obj-$(CONFIG_THERMAL)		+= thermal_sys.o
obj-$(CONFIG_CPU_THERMAL)       += cpu_cooling.o
obj-$(CONFIG_SPEAR_THERMAL)		+= spear_thermal.o
obj-$(CONFIG_SENSORS_EXYNOS4_TMU)	+= exynos4_thermal.o
obj-$(CONFIG_IMX6Q_THERMAL)		+= imx6q_thermal.o
