# Au1200/Au1550 PSC audio
snd-soc-au1xpsc-dbdma-objs := dbdma.o
snd-soc-au1xpsc-i2s-objs := psc-i2s.o
snd-soc-au1xpsc-ac97-objs := psc-ac97.o

obj-$(CONFIG_SND_SOC_AU1XPSC) += snd-soc-au1xpsc-dbdma.o
obj-$(CONFIG_SND_SOC_AU1XPSC_I2S) += snd-soc-au1xpsc-i2s.o
obj-$(CONFIG_SND_SOC_AU1XPSC_AC97) += snd-soc-au1xpsc-ac97.o

# Boards
snd-soc-exmmb-ac97-objs	:= exmmb-ac97.o
snd-soc-exmmb-i2s-objs	:= exmmb-i2s.o

obj-$(CONFIG_SND_SOC_EXM1200_AC97) += snd-soc-exmmb-ac97.o
obj-$(CONFIG_SND_SOC_EXM1200_SSI) += snd-soc-exmmb-i2s.o
